routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home', ['category_id' => request('category_id')]);
});

Route::get('/locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Auth::routes();

Route::resource('categories', 'CategoriesController')
    ->middleware('auth');

Route::resource('products', 'ProductsController')
    ->middleware('auth');

Route::resource('orders', 'OrdersController')
    ->middleware('auth');

Route::get('orders/create/{id?}', 'OrdersController@create')
    ->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use App\Events\EntityCreated;
use App\Events\EntityDeleted;
use App\Events\EntityUpdating;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $table = 'products';

    protected $fillable = ['name', 'description', 'photo', 'price', 'currency', 'category_id'];

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'created' => EntityCreated::class,
        'updating' => EntityUpdating::class,
        'deleted' => EntityDeleted::class,
    ];

    /**
     * return Category of product.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Return orders of products.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\ValidateProducts;
use App\Product;
use Illuminate\Support\Facades\Storage;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datos['products'] = Product::paginate(5);
        return view('products.index', $datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datos['categories'] = Category::all();
        return view('products.create', $datos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ValidateProducts $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidateProducts $request)
    {
        $product = $request->validated();

        if ($request->file('photo')) {
            $product['photo'] = $request->file('photo')->store('public/uploads');
            $product['photo'] = str_replace('public/uploads', 'uploads', $product['photo']);
        }

        Product::create($product);

        return redirect()->route('products.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $datos['categories'] = Category::all();

        return view('products.edit', $datos, compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ValidateProducts $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function update(ValidateProducts $request, $id)
    {
        $product = $request->validated();

        if ($request->file('photo')) {
            $oldProduct = Product::findOrFail($id);
            Storage::delete('public/' . $oldProduct->photo);
            $product['photo'] = $request->file('photo')->store('public/uploads');
            $product['photo'] = str_replace('public/uploads', 'uploads', $product['photo']);
        }

        Product::findOrFail($id)->update($product);

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::findOrFail($id)->delete();

        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('actions.create.action')
                    {{trans_choice('products.name',2)}}</div>
                <div class="card-body">
                    <form action="{{url('/products')}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        @include('products.form', ['type'=>'create'])
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('actions.edit.action')
                    {{trans_choice('products.name',2)}}</div>
                <div class="card-body">

                    <form action="{{url('/products/'.$product->id)}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}
                        @include('products.form', ['type'=>'editar'])
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/form.blade.php
<div>

    <div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('products.columns.name') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                    value="{{$product->name ?? ''}}" required autocomplete="name" autofocus>

                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="description"
                class="col-md-4 col-form-label text-md-right">{{ __('products.columns.description') }}</label>

            <div class="col-md-6">
                <input id="description" type="text" class="form-control @error('description') is-invalid @enderror"
                    name="description" value="{{$product->description ?? ''}}" required autocomplete="description"
                    autofocus>

                @error('description')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="mobile" class="col-md-4 col-form-label text-md-right">{{ __('products.columns.price') }}</label>

            <div class="col-md-6">
                <input id="price" type="float" class="form-control @error('price') is-invalid @enderror" name="price"
                    value="{{$product->price ?? ''}}" required autocomplete="price" autofocus>

                @error('price')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="currency" class="col-md-4 col-form-label text-md-right">{{ __('products.columns.currency') }}</label>

            <div class="col-md-6">
                <select value="{{$product->currency ?? ''}}" name="currency" id="currency"
                    class="form-control @error('currency') is-invalid @enderror" required autocomplete="currency"
                    autofocus>
                    <option value="">-- @lang('actions.options.combobox.default') --</option>
                    <option {{$product->currency ?? '' =='COP' ? ' selected ':''}} value="COP">{{__('currencys.cop')}}
                    </option>
                    <option {{$product->currency ?? ''=='USD' ? ' selected ':''}} value="USD">{{__('currencys.usd')}}
                    </option>
                </select>
                @error('currency')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="category" class="col-md-4 col-form-label text-md-right">{{ __('products.columns.category') }}</label>
            <div class="col-md-6">
                <select value="{{$product->category ?? ''}}" name="category_id" id="category"
                    class="form-control @error('category_id') is-invalid @enderror" required autocomplete="category_id"
                    autofocus>
                    <option value="">-- @lang('actions.options.combobox.default') --</option>
                    @foreach ($categories as $category)
                    <option {{ $product->category_id ?? ''== $category->id ? ' selected ':''}}
                        value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                @error('category_id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('products.columns.photo') }}</label>

            <div class="col-md-6">
                @if(isset($product->photo))
                <img src="{{ asset('storage').'/'.$product->photo}}" alt="" width="100">
                @endif

                <input id="photo" type="file" class="form-control @error('photo') is-invalid @enderror" name="photo"
                    accept="image/png, image/jpeg" value="{{$product->photo ?? ''}}" autocomplete="photo" autofocus>

                @error('photo')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <a class="btn btn-secondary"
                   href="{{route('products.index')}}">{{__('actions.options.button.return')}}</a>
                <button type="submit" class="btn btn-primary">
                    {{$type=='create'? __('actions.create.action'): __('actions.edit.action')}}
                </button>
            </div>
        </div>
    </div>

</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">

            <div class="card"  style="width: -webkit-fill-available;">
                <div class="card-header">
                    <div class="row justify-content-left">
                        <div class="col-sm-8">
                            <h1>@lang('products.title')</h1>
                        </div>
                        <div class="col-sm-4 pt-2 text-right" style="vertical-align: middle;">
                            <a class="btn btn-primary"
                               href="{{route('products.create')}}">@lang('actions.create.action')
                                {{trans_choice('products.name',2)}}</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <table class="table table-striped">
                        <thead class="thead">
                        <tr>
                            <th>@lang('products.columns.photo')</th>
                            <th>@lang('products.columns.name')</th>
                            <th>@lang('products.columns.description')</th>
                            <th>@lang('products.columns.price')</th>
                            <th>@lang('products.columns.actions')</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($products as $product)
                            <tr>
                                <td>
                                    @if($product->photo)
                                        <img src="{{ asset('storage').'/'.$product->photo}}" alt="" width="100">
                                    @else
                                        <img src="{{asset('img/no-image-icon.png')}}" alt="" width="100">
                                    @endif

                                </td>
                                <td>{{$product->name}}</td>
                                <td>{{$product->description}}</td>
                                <td>{{number_format($product->price, 2)}} {{$product->currency}}</td>
                                <td style="vertical-align: middle;">
                                    <div class="form-group row" style="width: max-content;">
                                        <a href="{{route('products.edit',$product->id)}}"
                                           class="btn btn-secondary m-2">@lang('actions.edit.action')</a>

                                        <form method="post" action="{{route('products.destroy',$product->id)}}">
                                            {{csrf_field()}}
                                            {{method_field('DELETE')}}
                                            <button class="btn btn-primary m-2" type="submit"
                                                    onclick="return confirm( '{{$product->name}}');">@lang('actions.delete.action')</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        @if(count($products)==0)
                            <tr>
                                <td colspan="6">@lang('products.columns.notFound')</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>

                    <div class="form-group row  justify-content-center">
                        {!!$products->render()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection